# Generated by Django 4.0.3 on 2022-04-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
