# Generated by Django 4.0.3 on 2022-04-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='firname',
            new_name='firstname',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profilepic',
            field=models.ImageField(default='user/default.png', upload_to='user/doctor/profile/'),
        ),
    ]
