# Generated by Django 4.0.3 on 2022-04-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_rename_firname_patient_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='postimages/')),
                ('category', models.CharField(choices=[('#mentalhealth', '#mentalhealth'), ('#heartdisease', '#heartdisease'), ('#covid19', '#covid19'), ('#immunization', '#immunization'), ('#medical', '#medical')], default='#medical', max_length=100)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.doctor')),
            ],
        ),
    ]
