# Generated by Django 4.0.3 on 2022-04-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_id',
            new_name='id',
        ),
    ]
